---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-repo
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: git@github.com:redbridge/openshift4-developer-workshop.git
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/app:latest