apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: build-and-deploy-pipelinerun-
spec:
  pipelineRef:
    name: build-and-deploy
  #serviceAccountName: robot-git-ssh
  resources:
    - name: app-repo
      resourceRef:
        name: app-repo
    - name: app-image
      resourceRef:
        name: app-image