apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/app:latest
          resources:
              requests:
                memory: "2048Mi"
                cpu: "250m"
              limits:
                memory: "2048Mi"
                cpu: "500m"
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8080
              protocol: TCP